apiVersion: batch/v1
kind: Job
metadata:
  name: llamaindex-ingest-data
spec:
  template:
    metadata:
      labels:
        name: ingest-data
      annotations:
        gke-gcsfuse/volumes: 'true'
    spec:
      serviceAccount: default
      containers:
      - name: ingest-data
        image: us-central1-docker.pkg.dev/peteryizhong-gke-dev/peteryizhong-repository/demo-app
        imagePullPolicy: Always
        command: ["python3", "cmd/ingest_data.py"]
        env:
        - name: INPUT_DIR
          value: /datalake
        - name: NEO4J_URI
          value: "bolt://neo4j:7687"
        - name: NEO4J_USERNAME
          value: "neo4j"
        - name: NEO4J_PASSWORD
          value: "password123"
        - name: OLLAMA_SERVER_URL
          value: "http://ollama-service:11434"
        volumeMounts:
        - name: datalake
          mountPath: /datalake
      volumes:
      - name: datalake
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: graphrag-eqwrnds
            mountOptions: implicit-dirs,only-dir=datalake
      restartPolicy: Never
  backoffLimit: 4